### ISSUE TITLE
Gracenote API SSLProtocolException

### ISSUE THREAD

**Issue by kanishkaganguly** [richadams/java-gracenote#1]
I am trying to run your example.java from the gracenote-java API but I am encountering the following error : 
javax.net.ssl.SSLProtocolException: Extensions not allowed in v2 certificate

Please help/

**Comment by richadams** [comment]
I'm unable to reproduce this, and I can't find any massively useful information on Google about it either. At least nothing that seems relevant in this case.

http://stackoverflow.com/questions/11684500/javax-net-ssl-sslprotocolexception-extensions-not-allowed-in-v2-certificate
http://stackoverflow.com/questions/9059196/accepting-certificates-in-java

There's nothing I'm doing in the code that's specific to SSL either. Not a very helpful answer, I know. Sorry I can't be more helpful :(
